-- search condtions 

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE CUSTOMER#>1005 ;

SELECT * FROM CUSTOMERS WHERE CUSTOMER# BETWEEN 1005 AND 1010;

SELECT * FROM CUSTOMERS WHERE CUSTOMER# IN(1005 ,1006,1007,1008,1009, 1010);

SELECT * FROM CUSTOMERS WHERE STATE IN ('NY','WA','CA');


SELECT  * FROM  CUSTOMERS WHERE  customer#>=1005 and customer#<=1010;

SELECT  * FROM CUSTOMERS  WHERE  customer#>1004 and customer#<1011;

SELECT * FROM  CUSTOMERS WHERE  customer#<1011 and customer#>1004;


-- LIST OF CUSTOMERS IN THE CITY OF AUSTIN
SELECT  * FROM CUSTOMERS where city ='AUSTIN';

--LIST OF CUSTOMERS WHO IS NOT IN CIYT OF  AUSTIN 

SELECT  * FROM CUSTOMERS WHERE city!='AUSTIN';
SELECT *  FROM CUSTOMERS  WHERE city<>'AUSTIN';
SELECT* FROM  CUSTOMERS  WHERE CITY ^='AUSTIN';

--LIST OF CUSTOMERS WHO DID NOT PROVIDE EMAIL ID 
SELECT * FROM  CUSTOMERS WHERE email is NULL;
-- INCORRECT QUERY: select * from customers where email='null';
SELECT * FROM  CUSTOMERS WHERE email is NOT null;
-- LIST OF CUSTOMERS BY CITY 

SELECT * FROM CUSTOMERS ORDER BY 5 ,2 DESC; 

SELECT * FROM CUSTOMERS ORDER BY 3;

SELECT * FROM CUSTOMERS WHERE REFERRED IS NOT NULL ;
SELECT * FROM CUSTOMERS WHERE REFERRED IS NOT NULL ORDER BY EMAIL,2;

 
 --% ANY NUMBER OF CHARACTER ,_ IS EXACTLY ONE CHARACTER
 
 SELECT * FROM CUSTOMERS WHERE LASTNAME LIKE'%N%';
 SELECT * FROM CUSTOMERS WHERE LASTNAME LIKE'N%';
SELECT * FROM CUSTOMERS WHERE LASTNAME LIKE '%N';

-- FIND CUSTOMERS WHOSE FIRSTNAME STARTS WITH L AND LASTNAME ENDS WITH H. 
SELECT * FROM CUSTOMERS where firstname like 'L%'and lastname like '_M%H';

SELECT * FROM CUSTOMERS WHERE LASTNAME LIKE 'M_R%';

SELECT * FROM CUSTOMERS WHERE LASTNAME  
LIKE '%N' AND STATE IN ('FL','MI') AND CITY LIKE 'C%';

SELECT * FROM BOOKS;

-- LIST OF BOOKS WITH IN THIS RANGE $30 -$50 IN FAMILY LIFE  CATEGORY 

SELECT * FROM  BOOKS WHERE cost BETWEEN 30 AND 50 AND CATEGORY LIKE 'F%';
SELECT * FROM BOOKS  WHERE cost BETWEEN 30 AND 50 AND CATEGORY='FAMILY LIFE';


-- DATE 
SELECT * FROM BOOKS WHERE PUBDATE <'17-JUL-04';

SELECT * FROM BOOKS WHERE COST >20 AND retail< 50;
SELECT * FROM BOOKS WHERE COST >20 OR  retail< 50;