select sysdate "date" from dual;
select ora_database_name from dual; --display database name


SELECT table_name
FROM user_tables
ORDER BY table_name;

SELECT table_name
FROM all_tables
ORDER BY table_name;

SELECT * FROM user_users;


/*DUAL is a table automatically created by Oracle Database along with the data dictionary. 
DUAL is in the schema of the user SYS but is accessible by the name DUAL to all users. 
It has one column, DUMMY , defined to be VARCHAR2(1) , and contains one row with a value X*/

select * from dual;
select 2+2 from dual;
DESCRIBE dual;

Describe  employee;
select emp_no as "Employee Number" , emp_name from employee;
select emp_no || ' ' || emp_name as "Employee details" from employee;

CREATE TABLE Emp (
 EMp_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 10,
 Emp_name VARCHAR2(100) not null,
 city VARCHAR2(30),
 Salary number,
 bonus number
 );

insert into EMp(emp_name,city,salary,bonus) values('zakiya','Brampton',2500000,130000);

insert into EMp(emp_name,city,salary,bonus) values('Midu','Brampton',500000,10000);

insert into EMp(emp_name,city,salary,bonus) values('sam','Toronto',1500000,120000);
insert into EMp(emp_name,city,salary,bonus) values('Rena','London',200000,10000);

insert into EMp(emp_name,city,salary,bonus) values('Jiya','Toronto',200000,10000);

select * from emp;

SELECT emp_name, bonus+salary As Bonuslalary FROM emp where bonus <15000;

CREATE TABLE users ( user_id INT PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE (username) );

select distinct salary from emp order by salary;

select city, sum(salary) from emp group by city;

select city, count(emp_id) from emp group by city;

select city, MAx(salary) from emp group by city having MAx(salary)>100000;

select city, Min(salary) from emp group by city;


